CREATE TABLE IF NOT EXISTS CLIENTE(
    ID_CLIENTE NUMERIC PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(200),
   TELEFONE VARCHAR(15)
);                           

ALTER TABLE CLIENTE
ADD CONSTRAINT